version = 1
SPDX-PackageName = "unified-control"
SPDX-PackageSupplier = "Sidings Media <contact@sidingsmedia.com>"

[[annotations]]
path = ["config/ingress/errors/**/*.http"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Sidings Media"
SPDX-License-Identifier = "CC-BY-SA-4.0"


